#!/usr/bin/env bash

show_welcome_message() {
    echo 'Welcome to the kubernetes cluster setup for Arkivverket'
    echo
    echo 'This program will create infrastructure in a public cloud (currently only Azure is supported)'
    echo
}


choose_tfstorage_name() {
    local storage_name

    echo 'You need to choose a name for where data about the cluster will be stored'
    echo 'This would typically be related to your project name'
    echo 'Also, it needs to be globally unique for the cloud provider'
    echo 'If you already have made some cluster(s) in your project you may reuse a name you have chosen earlier for that project'
    echo

    while true; do
        read -p "Please enter a name: " storage_name

        if [[ -z $storage_name ]]; then
            continue
        fi

        if [[ ${#storage_name} -lt 3 ]]; then
            echo "$storage_name is too short (must be at least 3 characters in length)"
            continue
        fi

        if [[ ${#storage_name} -gt 24 ]]; then
            echo "$storage_name is too long (must be at most 24 characters in length)"
            continue
        fi

        if [[ ! $storage_name =~ ^([a-z]|[0-9])+$ ]]; then
            echo "The project name must only contain lowercase letters and digits"
            continue
        fi

        echo "The name will be $storage_name"
        read -p "Is this OK? (y/n) "
        if [[ $REPLY =~ y(es)? ]]; then
            break
        fi
    done

    export STORAGE_ACCOUNT_NAME="$storage_name"
    export KEYVAULT_NAME="$storage_name"
}

main() {
    show_welcome_message
    choose_tfstorage_name

    azure/terraform-remote-state

    (cd azure && terraform apply)
}

main
