apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tusd
  template:
    metadata:
      labels:
        run: tusd
    spec:
      volumes:
        - name: gcs
          secret:
            secretName: gcs-cred

      containers:
      - name: tusd-container
        image: arkivverket.azurecr.io/mottak/tusd
        imagePullPolicy: Always
        ports:
        - containerPort: 1080
          protocol: TCP
        # GCS auth happends through a magic JSON file.
        livenessProbe:
          httpGet:
            path: /
            port: 1080
          initialDelaySeconds: 10
          periodSeconds: 10
        # If using GCS as a backend we must use the native interface
        # because of compat issues tusd <--> gcs
        env:
            # Override this if outside google:
            # If on AWS, this should be unset, methinks.
          - name: DBSTRING
            valueFrom:
              secretKeyRef:
                name: invitation-dsn
                key: invitation-dsn
          - name: MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: mailgun
                key: apiKey
          - name: MAILGUN_DOMAIN
            valueFrom:
              secretKeyRef:
                name: mailgun
                key: emailDomain
      - name: tusd-sidecar
        image: minio/minio
        # Requires Kubernetes 1.18
        # lifecycle:
        #   type: Sidecar
        ports: 
          - containerPort: 9000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: MINIO_ACCESS_KEY
            value: bleh
          - name: MINIO_SECRET_KEY
            value: bleh bleh bleh
  
