#!/usr/bin/env bash

readonly PROGRAM_NAME=${BASH_SOURCE##*/}

readonly RESOURCE_GROUP_NAME=arkivverket
readonly STORAGE_ACCOUNT_NAME=arkivverketwin
readonly CONTAINER_NAME=tfstate
readonly LOCATION=${LOCATION:-norwayeast}
readonly KEYVAULT_NAME=${KEYVAULT_NAME:-arkivverketvault}
readonly SECRET_KEY=tfstate-windows-storage-key

# vars changed by options - these are the defaults
OUTPUT=/dev/null
SUBSCRIPTION_ID=''

prt() {
    printf "%b\n" "$@"
}

errexit() {
    printf "%b\n" "$@"
    exit 1
}

is_installed() {
    hash "$1" 2> /dev/null
}

check_deps() {
    if ! is_installed jq; then
        errexit "Please install the jq command and rerun"
    fi

    if ! is_installed az; then
        errexit "Please install the az command and rerun"
    fi

    if ! is_installed terraform; then
        errexit "Please install the terraform command and rerun"
    fi
}

azure_login() {
    if ! az account show &> /dev/null; then
        if ! az login &> $OUTPUT; then
            errexit "Unable to log in to Azure"
        fi
    fi

    if [[ -n $SUBSCRIPTION_ID ]]; then
        prt "Using subscription $SUBSCRIPTION_ID"
        if ! az account set --subscription="$SUBSCRIPTION_ID" &> $OUTPUT; then
            errexit "Unable to set subscription to $SUBSCRIPTION_ID"
        fi
    fi
}

create_keyvault() {
    local keyvault_name="$1"
    local resource_group_name="$2"
    local location="$3"


    if ! az keyvault show --name "$keyvault_name" &> /dev/null; then
        prt "Creating keyvault $keyvault_name in $location"
        if ! az keyvault create                      \
             --resource-group "$resource_group_name" \
             --location "$location"                  \
             --name "$keyvault_name" &> $OUTPUT; then
            errexit "Could not create keyvault $keyvault_name"
        fi
    else
        prt "Reusing existing vault $keyvault_name"
    fi
}

store_secret_in_vault() {
    local key="$1"
    local value="$2"
    local keyvault_name="$3"

    prt "Saving secret at key $key into vault $keyvault_name"
    if ! az keyvault secret set --name "$key" --value "$value" --vault-name "$keyvault_name" &> $OUTPUT; then
        errexit "Could not add the secret for key $key into $keyvault_name"
    fi
}

create_resource_group() {
    local resource_group_name="$1"
    local location="$2"

    if [[ $(az group exists --name "$resource_group_name" | tr -d '\n') == false ]]; then
        prt "Creating resource group $resource_group_name in $location"
        if az group create --name "$resource_group_name" --location "$location" &> $OUTPUT; then
            errexit "Could not create resource group $resource_group_name"
        fi
    else
        prt "Reusing existing resource group $resource_group_name"
    fi
}

create_storage_account() {
    local storage_account_name="$1"
    local resource_group_name="$2"

    if account_json=$(az storage account check-name --name "$storage_account_name"); then
        if [[ $(echo "$account_json" | jq --raw-output .nameAvailable | tr -d '\n') == true ]]; then
            prt "Creating storage account $storage_account_name in the resource group $resource_group_name"
            if ! az storage account create               \
                 --resource-group "$resource_group_name" \
                 --name "$storage_account_name"          \
                 --sku Standard_LRS                      \
                 --encryption-services blob &> $OUTPUT; then
                errexit "Could not create $storage_account_name under resource group $resource_group_name"
            fi
        elif [[ $(echo "$account_json" | jq --raw-output .reason | tr -d '\n') == AlreadyExists ]]; then
            prt "Reusing existing storage account $storage_account_name"
        else
            errexit "$(echo "$account_json" | jq --raw-output .message)"
        fi
    else
        errexit "Checking storage account $storage_account_name failed"
    fi
}

get_storage_account_key() {
    local storage_account_name="$1"
    local resource_group_name="$2"

    # prints the storage account key
    az storage account keys list               \
       --resource-group "$resource_group_name" \
       --account-name "$storage_account_name"  \
       --query [0].value \
       -o tsv
}

create_blob_storage() {
    local container_name="$1"
    local storage_account_name="$2"
    local storage_account_key="$3"


    if [[ $(az storage container exists               \
               --name "$container_name"               \
               --account-name "$storage_account_name" \
               2> /dev/null | jq .exists | tr -d '\n') != true ]]; then
        prt "Creating blob storage for terraform state in $container_name under $storage_account_name"
        if ! az storage container create            \
             --name "$container_name"               \
             --account-name "$storage_account_name" \
             --account-key "$storage_account_key" &> $OUTPUT; then
            errexit "Could not create the container named $container_name under the account $storage_account_name"
        fi
    else
        prt "Reusing existing container $container_name"
    fi
}

show_help_and_quit() {
    prt "Usage: $PROGRAM_NAME [options]"
    prt
    prt "Options:"
    prt "  --help\t\t\tShows this help"
    prt "  --subscription subscriptionid Use the given subscription id"
    prt "  --verbose\t\t\tShow the output of actions taken"
    exit 0
}

parse_options() {
    while true; do
        case "$1" in
            --help)
                show_help_and_quit
                ;;
            --subscription)
                shift
                SUBSCRIPTION_ID="$1"
                ;;
            --verbose)
                OUTPUT=/dev/tty
                ;;
            *)
                break
        esac
        shift
    done
}


main() {
    parse_options "$@"

    check_deps

    azure_login
    create_resource_group "$RESOURCE_GROUP_NAME" "$LOCATION"

    create_keyvault "$KEYVAULT_NAME" "$RESOURCE_GROUP_NAME" "$LOCATION"

    create_storage_account "$STORAGE_ACCOUNT_NAME" "$RESOURCE_GROUP_NAME"
    local storage_account_key
    storage_account_key=$(get_storage_account_key "$STORAGE_ACCOUNT_NAME" "$RESOURCE_GROUP_NAME")
    create_blob_storage "$CONTAINER_NAME" "$STORAGE_ACCOUNT_NAME" "$storage_account_key"

    store_secret_in_vault "$SECRET_KEY" "$storage_account_key" "$KEYVAULT_NAME"


    local vm_name
    read -rp "Please enter the name of the virual machine: " vm_name

    local admin_username
    read -rp "Please enter the admin username: " admin_username

    local admin_password
    read -rsp "Please enter the admin password: " admin_password

    terraform init
    terraform apply -var "vm_name=$vm_name"                \
                    -var "admin_username=$admin_username"  \
                    -var "admin_password=$admin_password"
}

main "$@"
